name: Vulnerability Scan

on:
  push:

jobs:
  vulnerability-scan:
    name: Escaneo de vulnerabilidades en dependencias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias del proyecto
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Safety
        run: pip install safety

      - name: Ejecutar escaneo de vulnerabilidades
        run: safety check --full-report
        continue-on-error: true
