name: CI/CD Pipeline with Coverage Summary

on:
  push:
  pull_request:

jobs:
  build:
    name: Run Tests & Generate Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests y generar reporte de coverage
        run: |
          pytest --disable-warnings --cov=. --cov-report=xml:coverage.xml

      - name: Subir reporte de coverage como artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

  coverage:
    name: Publish Coverage Summary
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Descargar artifact de coverage
        uses: actions/download-artifact@v4
        with:
          name: coverage-report

      - name: Publicar resumen de cobertura en Job Summary
        run: |
          echo "## Resumen de Cobertura" >> $GITHUB_STEP_SUMMARY
          python -c "import xml.etree.ElementTree as ET; \
                     root = ET.parse('coverage.xml').getroot(); \
                     print('**Line Coverage:** {:.2%}'.format(float(root.attrib.get('line-rate', 0))))" >> $GITHUB_STEP_SUMMARY



  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout del código
  #       uses: actions/checkout@v3

  #     - name: Configurar Python y entorno virtual
  #       run: |
  #         python -m venv venv
  #         source venv/bin/activate
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Desplegar a Staging (Ejemplo)
  #       run: |
  #         source venv/bin/activate
  #         echo "Desplegando la aplicación..."
  #         uvicorn main:app --reload
