name: CI/CD Pipeline

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        run: |
          pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Desplegar a Staging (Ejemplo)
        run: |
          echo "Desplegando la aplicación..."
          # Aquí puedes incluir comandos para desplegar, por ejemplo:
          # docker build -t my-app .
          # docker run -d -p 8000:8000 my-app
          # O si usas otro servicio, sus comandos respectivos.
