name: CI/CD Pipeline

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests y obtener cobertura
        run: |
          pytest --disable-warnings --cov=. --cov-report=xml

      - name: Subir reporte a Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Solo necesario si el repo es privado


  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #     - name: Checkout del código
  #       uses: actions/checkout@v3

  #     - name: Configurar Python y entorno virtual
  #       run: |
  #         python -m venv venv
  #         source venv/bin/activate
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: Desplegar a Staging (Ejemplo)
  #       run: |
  #         source venv/bin/activate
  #         echo "Desplegando la aplicación..."
  #         uvicorn main:app --reload
